alias: RGB Lightbulb As Load Meter
description: Change an RGB light to reflect a sensor value
triggers:
  - seconds: /20
    trigger: time_pattern
conditions:
  - condition: template
    value_template: |-
      {{ current_power > power_threshold_low and  
         current_power <= power_threshold_high }}  
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: |-
              {{ current_power >= default_power_low and  
                 current_power < default_power_high }}  
        sequence:
          - target:
              entity_id: light.athom_rgbct_light_9adff8_rgbcct_bulb
            data:
              rgb_color:
                - 10
                - 10
                - 10
              brightness: 0
              transition: 4
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: |-
              {{ current_power > power_threshold_low and  
                 current_power <= power_threshold_high }}  
        sequence:
          - target:
              entity_id: light.athom_rgbct_light_9adff8_rgbcct_bulb
            data:
              hs_color:
                - >-
                  {{ ((1-min([1,(current_power / power_threshold_high)])) * 120)
                  | round(0) }}  
                - 100
              brightness: 138
              transition: 4
            action: light.turn_on
mode: single
variables:
  power_sensor: sensor.sh15t_a2452418716_total_load_active_power
  power_threshold_low: 0
  power_threshold_high: 7
  default_power_low: 0
  default_power_high: 0.1
  rest_color:
    - 0
    - 0
    - 0
  rest_brightness: 0
  active_brightness: 138
  current_power: "{{ states(power_sensor) | float }}"
  update_interval: 20
  energy_lights: light.athom_rgbct_light_9adff8_rgbcct_bulb
